### ISSUE TITLE
DOI not matching entry

### ISSUE THREAD

**Issue by oospina** [pachterlab/LP_2021#2]
It looks like the DOI of "Single-cell atlas of lineage states, tumor microenvironment and subtype-specific expression programs in gastric cancer" (rows 216 and 217 of the Google spreadsheet) should be:
10.1158/2159-8290.CD-21-0683
and not:
10.3390/cancers13194837

**Comment by lambdamoses** [comment]
Thanks for pointing that out. I have corrected that DOI.
