### ISSUE TITLE
'View source' and 'Edit this page' links broken

### ISSUE THREAD

**Issue by PeteHaitch** [pachterlab/LP_2021#3]
E.g., clicking either link from https://pachterlab.github.io/LP_2021/prequel.html goes to https://github.com/pachterlab/LP_2021/tree/main/supplement/blob/master/02-prequel.Rmd, which leads to a 404 error.
I think the link should be https://github.com/pachterlab/LP_2021/blob/main/supplement/02-prequel.Rmd but I don't know enough **bookdown** to fix, sorry.

**Comment by lambdamoses** [comment]
Thanks for notifying us. I have never clicked those links myself. Now it has been fixed.
