### ISSUE TITLE
Change breaks in the x axis in smFISH number of cells and number of genes through time plot

### ISSUE THREAD

**Issue by lambdamoses** [pachterlab/LP_2021#6]
The x axis has one label every 5 years. It would look better if it's 2 years.

**Comment by qqyybl** [comment]
Hello
Please remove my email from the subscription list.
Thank you.

Yours sincerely
Yin

On Feb 17, 2024, at 05:47, Lambda Moses ***@***.***> wrote:

﻿

The x axis has one label every 5 years. It would look better if it's 2 years.

**Comment by lambdamoses** [comment]
I can't remove you but you can remove yourself by unwatching this repo. The "unwatch" button should be in the row of buttons near the top right corner of the Code pane when you visit the webpage of this repo.
