### ISSUE TITLE
Paper Update

### ISSUE THREAD

**Issue by oospina** [pachterlab/LP_2021#9]
The bioRxiv describing the web application spatialGE is now published in Cancer Research:

https://doi.org/10.1158/0008-5472.CAN-24-2346

The entry in reference is:

https://doi.org/10.1101/2024.06.27.601050 (bioRxiv)

Also, I noticed there is a comment on the app's usability. However, I would like to clarify that we put the app code in the GitHub repo for transparency purposes and that it is not intended to be installed by users. The "user-friendliness" lies in the web server hosting the app (https://spatialge.moffitt.org). We apologize for the confusion.

Oscar

**Comment by lambdamoses** [comment]
I updated the entry. Congrats for getting it published!
